version: "3.8"
services:
  inventory-app:
    container_name: inventory-app
    build: .
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - blissful_hermann
      
  blissful_hermann:
    container_name: blissful_hermann
    image: "mysql"
    restart: always
    hostname: blissful_hermann
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root